import { Popover, Button } from 'antd';
import CustomAvatar from '../custom-avatar';
import { useGetIdentity } from '@refinedev/core';

import type { User } from '@/graphql/schema.types'; // docs: generated by GraphQL Codegen

const CurrentUser = () => {
  const { data: user } = useGetIdentity<User>();

  return (
    <>
      <Popover
        placement="bottomRight"
        trigger={'click'}
        overlayInnerStyle={{ padding: 0 }}
        overlayStyle={{ zIndex: 999 }}
      >
        <CustomAvatar name="AA" />
      </Popover>
    </>
  );
};

export default CurrentUser;
